### ISSUE TITLE
Error when installing via pip

### ISSUE THREAD

**Issue by mammuth** [Blueshoe/djangocms-layouter#5]
```
pip install djangocms-layouter                                                                                            
Collecting djangocms-layouter
/home/mmuth/PycharmProjects/mpicc-demo/env/local/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
  Downloading djangocms-layouter-0.1.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-build-LMWCat/djangocms-layouter/setup.py", line 36, in <module>
        long_description = read('README.rst'),
      File "/tmp/pip-build-LMWCat/djangocms-layouter/setup.py", line 6, in read
        return open(os.path.join(os.path.dirname(__file__), fname)).read()
    IOError: [Errno 2] No such file or directory: '/tmp/pip-build-LMWCat/djangocms-layouter/README.rst'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-LMWCat/djangocms-layouter

```
I'm running this from within a virtualenv with 9.0.1

Looks related to #1

**Comment by mammuth** [comment]
Installing it directly from GitHub works via:
`pip install -e git+https://github.com/Blueshoe/djangocms-layouter#egg=layouter`

However it results in an runtime error, so I guess the setup doesn't work flawlessly this way.
```
env/src/layouter/layouter/templates/layouter/container.html, error at line 21
NoReverseMatch: u'layouter' is not a registered namespace
```
